version: '3'
services:

  gps:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240815-a9106
    command: ./components/drivers/gps_component_main
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  imu:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240815-a9106
    command: ./components/drivers/imu_component_main
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  record:
    depends_on:
      - gps
      - imu
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240815-a9106
    command: ./external/dm_wurmloch/tools/wurmloch_recorder/wurmloch_recorder record --output ./record/ -a
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - /home/cat/Data:/work/record
