version: '3'
services:

  gps:
    image: aliyunregistry-gz-mobi-registry.cn-guangzhou.cr.aliyuncs.com/dm/mobili-app-amd64:presubmit-20240919-f398b
    command: ./components/drivers/rtk_component_main --config_file ./launch/xavier_local/rk3566_drivers_rtk.proto.txt
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  imu:
    image: aliyunregistry-gz-mobi-registry.cn-guangzhou.cr.aliyuncs.com/dm/mobili-app-amd64:presubmit-20240919-f398b
    command: ./components/drivers/imu_component_main --config_file ./launch/xavier_local/rk3566_drivers_imu.proto.txt
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  pose_server:
    depends_on:
      - gps
      - imu
    image: aliyunregistry-gz-mobi-registry.cn-guangzhou.cr.aliyuncs.com/dm/mobili-app-amd64:presubmit-20240919-f398b
    privileged: true
    entrypoint: /bin/bash -c "echo 'wait 8s for gps and imu'; sleep 8; ./components/map/pose_server_component_main --config_file ./launch/xavier_local/msp20_pose_server_rk3566_boat.proto.txt -stop_stablize true"
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - /home/dmgz/Data:/work/record

  record:
    depends_on:
      - gps
      - imu
      - pose_server
    image: aliyunregistry-gz-mobi-registry.cn-guangzhou.cr.aliyuncs.com/dm/mobili-app-amd64:presubmit-20240919-f398b
    privileged: true
    entrypoint: /bin/bash -c "echo 'wait 8s for gps、imu and pose_server'; sleep 8; ./external/dm_wurmloch/tools/wurmloch_recorder/wurmloch_recorder record --output ./record/ -a"
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - /home/dmgz/Data:/work/record
