version: '3'
services:

  gps:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app-amd64:presubmit-20240702-d87fa
    command: ./components/drivers/gps_component_main
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
    

  imu:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app-amd64:presubmit-20240702-d87fa
    command: ./components/drivers/imu_component_main
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev


  record:
    depends_on:
      - gps
      - imu
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app-amd64:presubmit-20240702-d87fa
    privileged: true
    entrypoint: /bin/bash -c "echo 'wait 8s for gps and imu'; sleep 8; ./external/dm_wurmloch/tools/wurmloch_recorder/wurmloch_recorder record --output ./record/ -a"
    


