version: '3'
services:

  gps:
    image: 431983620723.dkr.ecr.ap-east-1.amazonaws.com/dm/mobili-app:presubmit-20240919-f398b
    command: ./components/drivers/gps_component_main --config_file ./launch/xavier_local/rk3566_drivers_gps.proto.txt
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  imu:
    image: 431983620723.dkr.ecr.ap-east-1.amazonaws.com/dm/mobili-app:presubmit-20240919-f398b
    command: ./components/drivers/imu_component_main --config_file ./launch/xavier_local/rk3566_drivers_imu.proto.txt
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  record:
    depends_on:
      - gps
      - imu
    image: 431983620723.dkr.ecr.ap-east-1.amazonaws.com/dm/mobili-app:presubmit-20240919-f398b
    command: ./external/dm_wurmloch/tools/wurmloch_recorder/wurmloch_recorder record --output ./record/ -a
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - /home/cat/Data:/work/record
