version: '3'
services:

  gps:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app-amd64:presubmit-20240914-5a2f2
    command: ./components/drivers/gps_component_main --config_file ./launch/xavier_local/rk3566_drivers_gps.proto.txt
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  imu:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app-amd64:presubmit-20240914-5a2f2
    command: ./components/drivers/imu_component_main --config_file ./launch/xavier_local/rk3566_drivers_imu.proto.txt
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  record:
    depends_on:
      - gps
      - imu
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app-amd64:presubmit-20240914-5a2f2
    privileged: true
    entrypoint: /bin/bash -c "echo 'wait 8s for gps and imu'; sleep 8; ./external/dm_wurmloch/tools/wurmloch_recorder/wurmloch_recorder record --output ./record/ -a"
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - /home/dmgz/Data:/work/record
