version: '3'
services:

  gps:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240802-605a4
    command: ./components/drivers/gps_component_main
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  imu:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240802-605a4
    command: ./components/drivers/imu_component_main
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime

  pose_server:
    depends_on:
      - gps
      - imu
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240802-605a4
    # network_mode: "host"  用来共享所有端口，不确定有没有用
    ports:
      - "40010:40010"
    privileged: true
    entrypoint: /bin/bash -c "echo 'wait 8s for gps and imu'; sleep 8; ./components/map/pose_server_component_main --config_file ./launch/xavier_local/msp20_pose_server_rk3566.proto.txt -stop_stablize true"
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - /home/cat/Data:/work/record

  record:
    depends_on:
      - gps
      - imu
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240802-605a4
    command: ./external/dm_wurmloch/tools/wurmloch_recorder/wurmloch_recorder record --output ./record/ -a
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - /home/cat/Data:/work/record
