version: '3'
services:

  gps:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240719-24088
    command: ./components/drivers/gps_component_main
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
    

  imu:
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240719-24088
    command: ./components/drivers/imu_component_main
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime


  record:
    depends_on:
      - gps
      - imu
    image: aliyunregistry.deepmirror.com.cn/dm/mobili-app:presubmit-20240719-24088
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - /home/cat/Data:/work/record
      


